sudo: required
language: crystal
before_install:
  - sudo apt-get install -qy m4 make autoconf automake libtool
  - wget https://github.com/xapian/xapian/archive/v1.3.5.tar.gz -O /tmp/xapian.tar.gz
  - tar xzvf /tmp/xapian.tar.gz -C /tmp
  - cd /tmp/xapian-1.3.5 && ./bootstrap --without-autotools xapian-core
  - cd /tmp/xapian-1.3.5/xapian-core && ./configure --prefix=/usr --enable-maintainer-mode && make && sudo make install
  - wget https://github.com/endlessm/xapian-glib/archive/Release_2.6.0.tar.gz -O /tmp/xapian-glib.tar.gz
  - tar xzvf /tmp/xapian-glib.tar.gz -C /tmp
  - cd /tmp/xapian-glib-Release_2.6.0 && ./autogen.sh && ./configure --prefix=/usr && make && sudo make install
script:
  - make spec
