sudo: required
language: crystal
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update; sudo apt-get install -yq gcc-4.8 g++-4.8 uuid-dev
  - sudo mv /usr/bin/gcc-4.8 /usr/bin/gcc
  - sudo mv /usr/bin/g++-4.8 /usr/bin/g++
  - wget http://oligarchy.co.uk/xapian/1.3.5/xapian-core-1.3.5.tar.xz -O /tmp/xapian-core.tar.xz
  - tar xaf /tmp/xapian-core.tar.xz -C /tmp
  - cd /tmp/xapian-core-1.3.5 && ./configure --prefix=/usr && make && sudo make install
  - wget https://github.com/endlessm/xapian-glib/archive/Release_2.6.0.tar.gz -O /tmp/xapian-glib.tar.gz
  - tar xzf /tmp/xapian-glib.tar.gz -C /tmp
  - cd /tmp/xapian-glib-Release_2.6.0 && ./autogen.sh && ./configure --prefix=/usr && make && sudo make install
script:
  - make spec
